# Generated by Django 5.2.7 on 2026-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercar',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Атмосферний'), ('TURBO', 'Турбований'), ('SUPERCHARGE', 'Наддувний')], max_length=20, null=True, verbose_name='Тип двигуна'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="Об'єм двигуна (л)"),
        ),
        migrations.AddField(
            model_name='usercar',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('GASOLINE', 'Бензин'), ('DIESEL', 'Дизель'), ('LPG', 'Газ/Газ-бензин'), ('ELECTRIC', 'Електро'), ('HYBRID', 'Гібрид'), ('CNG', 'Метан')], max_length=20, null=True, verbose_name='Тип палива'),
        ),
        migrations.AddField(
            model_name='usercar',
            name='technical_condition',
            field=models.CharField(choices=[('EXCELLENT', 'Відмінний'), ('GOOD', 'Добрий'), ('NEEDS_REPAIR', 'Потребує ремонту'), ('CRITICAL', 'Критичний')], default='GOOD', max_length=20, verbose_name='Технічний стан'),
        ),
    ]
