# Generated by Django 6.0.2 on 2026-03-17 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='Від адміністратора')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат повідомлення',
                'verbose_name_plural': 'Чат повідомлення',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('OIL', 'Заміна оливи'), ('TIRE', 'Ротація шин'), ('INSPECTION', 'Техогляд'), ('BRAKE', 'Перевірка гальм'), ('AC', 'Обслуговування кондиціонера'), ('GENERAL', 'Загальне ТО')], max_length=20, verbose_name='Тип нагадування')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('reminder_date', models.DateTimeField(verbose_name='Дата нагадування')),
                ('mileage_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробіг для нагадування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Відправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cars.usercar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Нагадування',
                'verbose_name_plural': 'Нагадування',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оцінка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Схвалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='cars.usercar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
