# Generated by Django 6.0.2 on 2026-03-17 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Бали')),
                ('total_earned', models.PositiveIntegerField(default=0, verbose_name='Всього зароблено')),
                ('total_spent', models.PositiveIntegerField(default=0, verbose_name='Всього витрачено')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Рівень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бонусний рахунок',
                'verbose_name_plural': 'Бонусні рахунки',
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Кількість балів')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Зараховано'), ('SPEND', 'Витрачено')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бонусна транзакція',
                'verbose_name_plural': 'Бонусні транзакції',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(verbose_name='Дата послуги')),
                ('service_type', models.CharField(max_length=200, verbose_name='Тип послуги')),
                ('description', models.TextField(verbose_name='Опис робіт')),
                ('mileage_at_service', models.PositiveIntegerField(verbose_name='Пробіг на момент ТО')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантія до')),
                ('mechanic_notes', models.TextField(blank=True, verbose_name='Нотатки механіка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='bookings.booking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='cars.usercar')),
            ],
            options={
                'verbose_name': 'Історія ТО',
                'verbose_name_plural': 'Історія ТО',
                'ordering': ['-service_date'],
            },
        ),
    ]
